feat: separating gateway and docker
Gil4rt/java-shareit pull request #6
Opened 2023-02-26 01:15 UTC by Gil4rt

2023-02-26 21:56 UTC, andrew-larkin requested changes
Привет! Очень качественная реализация, прозрачная архитектура и хорошее покрытие тестами. Остается внести пару корректировок и можно будет переходить к дипломному проекту. Есть еще пара моментов, которые я не добавил в комменты к коду: 1) если коммент встречается один раз, например, в контроллере, то, по идее, он относится ко всем контроллерам; 2) @Repository над репозиториями - добавлена в одном месте, давай в остальных тоже добавим; 3) nativeQuery в репозиториях - в целом, нормально, но если вдруг мы поменяем БД от постгреса на другую, могут возникнуть конфликты на этой почве. предпочтительнее использовать jpql - одинаково воспринимается всеми базами данных. Но это только на твое усмотрение.

2023-02-26 21:56 UTC, andrew-larkin commented on docker-compose.yml
> +    build: ./gateway
для сервисов еще будет хорошо добавить настройку restart on failure - чтобы если упадет один, и он сам, и другие смогли бы запуститься еще раз

2023-02-26 21:56 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private final BookingService service;
в аргументах методов контроллера лучше не использовать примитивы. потому что если вдруг придет null, то мы словим NPE, а если будем использовать wrappers, то у нас есть возможность проверить приходящий параметр перед тем как отпускать его в сервис

2023-02-26 21:56 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.updateItem(id, itemDto, userId).map(updatedItem -> new ResponseEntity<>(updatedItem, HttpStatus.OK))
маппинг лучше, конечно, перенести в сервис. Чтобы сохранялась single responsability, в методах контроллеров должны вызываться методы сервиса и никакой доп логики, чтобы сохранить контроллер тонким/легковесным

2023-02-26 21:56 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Collection<Item> searchItems(@RequestParam(required = false) String text) {
вообще, возвращать сущность в ответе - плохая практика. по идее, возвращаться в ответе должны именно dto, даже если dto полностью повторяет поля сущности

2023-02-27 01:25 UTC, Gil4rt commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.updateItem(id, itemDto, userId).map(updatedItem -> new ResponseEntity<>(updatedItem, HttpStatus.OK))
Правильно ли будет то, что я в service маплю до ResponseEntity и уже после возвращаю контроллеру, или есть другой способ?

2023-02-28 13:18 UTC, merged